package eisbw;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;

public class WindowsTools {

  /**
   * Check if a process is running on the system.
   * @param process the name of the process.
   * @return true iff a process is running.
   */
  public static boolean isProcessRunning(String process) {
    try {
      Process proc = Runtime.getRuntime().exec("tasklist.exe");
      BufferedReader stdInput = new BufferedReader(new InputStreamReader(proc.getInputStream()));

      String line;
      while ((line = stdInput.readLine()) != null) {
        if (line.contains(process)) {
          return true;
        }
      }
    } catch (IOException exception) {
      exception.printStackTrace();
    }

    return false;
  }

  /**
   * Starts the Chaoslauncher with launch rules.
   * @param race the race specified in the mas2g
   * @param map the map specified in the mas2g
   * @param scDir the starcraft installation directory in the mas2g.
   * @throws IOException throws exception when BWAPI.ini cannot be written.
   */
  public static void startChaoslauncher(String race, String map, String scDir) throws IOException {
    populateInitFile(race, map, scDir);
    Runtime.getRuntime().exec(scDir + "\\Chaoslauncher\\Chaoslauncher.exe", null,
        new File(scDir + "\\Chaoslauncher\\"));
  }

  private static void populateInitFile(String race, String map, String scDir) {
    String newLine = System.getProperty("line.separator");
    String bwapiDest = scDir + "\\bwapi-data\\bwapi.ini";

    String iniFile = "";

    iniFile += ";Generated by GOAL launcher" + newLine;

    iniFile += "[ai]" + newLine;
    iniFile += "ai     = NULL" + newLine + newLine;

    iniFile += "[auto_menu]" + newLine;
    iniFile += "auto_menu = SINGLE_PLAYER" + newLine + newLine;

    iniFile += "pause_dbg = OFF" + newLine + newLine;

    iniFile += "auto_restart = OFF" + newLine + newLine;

    iniFile += "map = maps\\sscai\\" + map + newLine + newLine;

    iniFile += "race = " + race + newLine + newLine;

    iniFile += "enemy_count = 1" + newLine + newLine;

    iniFile += "enemy_race = Random" + newLine + newLine;

    iniFile += "[config]" + newLine;

    iniFile += "[window]" + newLine;
    iniFile += "windowed = ON" + newLine;
    iniFile += "width  = 1024" + newLine;
    iniFile += "height = 768" + newLine + newLine;

    try {
      BufferedWriter out = new BufferedWriter(new FileWriter(new File(bwapiDest)));
      out.write(iniFile);
      out.close();
    } catch (Exception exception) {
      System.err.println("Error: " + exception.getMessage());
    }
  }
}
